name: Style Check

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Check Black formatting
      run: |
        black --check --config pyproject.toml .

    - name: Check Import sorting
      run: |
        isort --check-only --diff --settings-path pyproject.toml . 
